問題集コンポーネントを作成しました。Front/14
swkoubou/HackU2021 pull request #24
Opened 2021-08-31 07:50 UTC by x0y14

## 変更点

- 問題集用のコンポーネント、QuestionCollection .vueを作成しました。
- testdata/question.jsonに、問題集用のデータを追加しました。
- ComponentsPreviewに問題集のサンプルを表示するようにしました。

## 対応するissue

closed #14

2021-09-01 04:30 UTC, nanagami1369 requested changes

2021-09-01 04:30 UTC, nanagami1369 commented on go/index.html
> +hogehoge
謎のファイルが上がっています

2021-09-02 05:03 UTC, x0y14 commented
最新のdevelopブランチをマージし、コンフリクトを解決し、goフォルダーにあったindex.htmlを削除しました。

2021-09-02 06:07 UTC, nanagami1369 approved these changes
Okです。

2021-09-02 06:07 UTC, merged